---
title: "ultraclean_alphadiversity_analyses"
author: "Anbu Poosakkannu"
date: "3/5/2020"
output: html_document
---

```{r setup, include=FALSE}
#load the required libraries for the analyses

library(microbiomeSeq); packageVersion("microbiomeSeq") #require for the alphadiversity analyses 




```


```{r}

#uplopad the data files for the analyses

#Read the OTU file
abund_table<-read.csv("D:/Czech/triatomine_manuscript/MS-Triatominae/data/Ultradata/otu_ultraclean_abund.csv",row.names=1,check.names=FALSE)#change the path for your computer

#transpose the OTU abundance data to have sample names on rows
abund_table<-t(abund_table)

#Read in the complete meta data file
meta_table<-read.csv("D:/Czech/triatomine_manuscript/MS-Triatominae/data/Ultradata/ultrameta_28022020.csv",row.names=1,check.names=FALSE)#change the path for your computer

#Read the taxonomy
OTU_taxonomy<-read.csv("D:/Czech/triatomine_manuscript/MS-Triatominae/data/Ultradata/otu_ultraclean_taxa.csv",row.names=1,check.names=FALSE)#change the path for your computer


#colnames(meta_table)<-c("ReadCount", "Plate", "WellPosition", "Organism", "State",
  #                      "Tcruzi","Host_Taxa", "Instar", "Instar_range", "Sex", "Locality",
   #                     "Nest", "Latitude", "Longitude", "Sample")




```


```{r}
###  1.1 - Phyloseq adaptation + cleanup
#Convert the data to phyloseq format
OTU = otu_table(as.matrix(abund_table), taxa_are_rows = FALSE)
TAX = tax_table(as.matrix(OTU_taxonomy))
SAM = sample_data(meta_table)
physeq<-merge_phyloseq(phyloseq(OTU, TAX),SAM)

clean_data<-physeq
#column names of taxonomy file
colnames(tax_table(clean_data))



```


```{r}
# Create some new subsets for later use here:
rubida_rarefy <- clean_data %>% subset_samples(Host_Taxa == "Trubida")
chaparral <- clean_data %>% subset_samples(Locality == "Chaparral")
tucson <- clean_data %>% subset_samples(Locality == "UADS" | Locality == "LCNCA")
young <- clean_data %>% subset_samples(Instar == "L1"|Instar == "L2"|Instar == "L3")


```



```{r}
### Species-specific ontogeny
Rubida <- clean_data %>% subset_samples(Host_Taxa == "Trubida")
Figure1B <-plot_anova_diversity(Rubida, method = c("richness", "shannon"), 
                          grouping_column = "Instar", pValueCutoff = 0.05)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/alphadiversity_analyses/Figure1B.pdf",width=8)#change the path for your computer
print(Figure1B)
dev.off()


protracta <- clean_data %>% subset_samples(Host_Taxa == "Tprotracta")
Supplementing_Figure_1B_B <- plot_anova_diversity(protracta, method = c("richness", "shannon"), 
                           grouping_column = "Instar", pValueCutoff = 0.05)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/alphadiversity_analyses/Supplementing_Figure_1B_B.pdf",width=8)#change the path for your computer
print(Supplementing_Figure_1B_B)
dev.off()


gerst <- clean_data %>%  subset_samples(Host_Taxa == "Tgerstaeckeri")
Supplementing_Figure_1B_A <- plot_anova_diversity(gerst, method = c("richness", "shannon"), 
                           grouping_column = "Instar", pValueCutoff = 0.05)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/alphadiversity_analyses/Supplementing_Figure_1B_A.pdf",width=8)#change the path for your computer
print(Supplementing_Figure_1B_A)
dev.off()


lect <- clean_data %>% subset_samples(Host_Taxa == "Tlecticularia")
Supplementing_Figure_1B_D <- plot_anova_diversity(lect, method = c("richness", "shannon"),
                           grouping_column = "Instar", pValueCutoff = 0.05)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/alphadiversity_analyses/Supplementing_Figure_1B_D.pdf",width=8)#change the path for your computer
print(Supplementing_Figure_1B_D)
dev.off()


sang <- clean_data %>% subset_samples(Host_Taxa == "Tsanguisuga")
Supplementing_Figure_1B_C <- plot_anova_diversity(sang, method = c("richness", "shannon"),
                           grouping_column = "Instar", pValueCutoff = 0.1)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/alphadiversity_analyses/Supplementing_Figure_1B_C.pdf",width=8)#change the path for your computer
print(Supplementing_Figure_1B_C)
dev.off()

```

