---
title: "homogeneity_analyses"
author: "Anbu Poosakkannu"
date: "6/15/2020"
output: html_document
---

```{r setup}
#load the required libraries for the analyses

library(phyloseq); packageVersion("phyloseq") #need for ordination analyses
library(ggplot2); packageVersion("ggplot2") #need for plotting graphs
library(dplyr); packageVersion("dplyr") #require to filter and clean up the data
library(vegan); packageVersion("vegan") #community analysis

```



```{r}
#uplopad the data files for the analyses

#Read the OTU file
abund_table<-read.csv("D:/Czech/triatomine_manuscript/MS-Triatominae/data/Ultradata/otu_ultraclean_abund.csv",row.names=1,check.names=FALSE)#change the path for your computer

#transpose the OTU abundance data to have sample names on rows
abund_table<-t(abund_table)

#Read in the complete meta data file
meta_table<-read.csv("D:/Czech/triatomine_manuscript/MS-Triatominae/data/Ultradata/ultrameta_28022020.csv",row.names=1,check.names=FALSE)#change the path for your computer

#Read the taxonomy
OTU_taxonomy<-read.csv("D:/Czech/triatomine_manuscript/MS-Triatominae/data/Ultradata/otu_ultraclean_taxa.csv",row.names=1,check.names=FALSE)#change the path for your computer


#colnames(meta_table)<-c("ReadCount", "Plate", "WellPosition", "Organism", "State",
  #                      "Tcruzi","Host_Taxa", "Instar", "Instar_range", "Sex", "Locality",
   #                     "Nest", "Latitude", "Longitude", "Sample")




```


```{r}
#Phyloseq adaptation
#Convert the data to phyloseq format
OTU = otu_table(as.matrix(abund_table), taxa_are_rows = FALSE)
TAX = tax_table(as.matrix(OTU_taxonomy))
SAM = sample_data(meta_table)
physeq<-merge_phyloseq(phyloseq(OTU, TAX),SAM)


#remove "NA" in Hosttaxa_instarrange of ultra_physeq
physeq <- physeq %>% 
  subset_samples(Host_instarrange != "NA") %>%
  prune_taxa(taxa_sums(.) > 0, .)



```



```{r}


# Set.seed for randomisation, making results reproducible
set.seed(5)

# Scale reads to even depth 
physeq_rarefy <- rarefy_even_depth(physeq, sample.size = 1000)

physeq_rarefy


```


```{r}
#ordination analyses using jaccard

physeq_rarefy_jaccard <- distance(physeq_rarefy, "jaccard")
physeq_rarefy_df <- as(sample_data(physeq_rarefy), "data.frame")
p2 <- plot_ordination(physeq_rarefy, physeq_rarefy_jaccard, color = "Instar_range")
p2 + theme_bw() + theme(text = element_text(size = 16)) + geom_point(size = 4) + stat_ellipse(aes(group =Instar_range))
p2


#Permanova for the instar range in whole ultra dataset
adonis_Instar_range <- adonis(physeq_rarefy_jaccard ~ Instar_range, data = physeq_rarefy_df)
adonis_Instar_range

#betadiseprsion for the instar range in whole dataset
groups <- physeq_rarefy_df[["Instar_range"]]
mod <- betadisper(physeq_rarefy_jaccard, groups)
anova(mod)

#the dispersion is different between groups, then examine
plot(mod)

pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/ordination_analyses/Additional_File_5.pdf",width=8)#change the path for your computer
print(Additional_File_5<-boxplot(mod))
dev.off()



```

