---
title: "ultracleandata_script"
author: "Anbu Poosakkannu"
date: "6/16/2020"
output: html_document
---

#load required packages

```{r}
#load the required packages

library(phyloseq) #needed for proper microbiome analysis
library(vegan) #community ecology analyses
library(ggplot2) #graphs
library(dplyr) #to filter and clean up the data
library(cowplot) #multiple ggplots
library(viridis) #colour package
library(microbiomeSeq) #required for alpha diversity analyses

```

#Upload input files

```{r}
#upload the input files for analyses

#Read the OTU file
abund_table<-read.csv("D:/Czech/triatomine_manuscript/MS-Triatominae/data/data_joel_ultra/otu_ultraclean_abund.csv",row.names=1,check.names=FALSE)

#transpose the OTU abundance data to have sample names on rows
abund_table<-t(abund_table)

#Read in the complete meta data file
meta_table<-read.csv("D:/Czech/triatomine_manuscript/MS-Triatominae/data/data_joel_ultra/meta_ultraclean.csv",row.names=1,check.names=FALSE)

#Read the taxonomy
OTU_taxonomy<-read.csv("D:/Czech/triatomine_manuscript/MS-Triatominae/data/data_joel_ultra/otu_ultraclean_taxa.csv",row.names=1,check.names=FALSE)


```

#Phyloseq object adaptation

```{r}
### create phyloseq object and subset required samples

#Convert the data to phyloseq format
OTU = otu_table(as.matrix(abund_table), taxa_are_rows = FALSE)
TAX = tax_table(as.matrix(OTU_taxonomy))
SAM = sample_data(meta_table)
physeq<-merge_phyloseq(phyloseq(OTU, TAX),SAM)

clean_data<-physeq

#remove the outlier sample from phyloseq object 
clean_data<-subset_samples(clean_data, SampleID != "TU50i3B3")


# Set.seed for randomisation, making results reproducible
set.seed(5)



```


#Alpha diversity analyses for each taxa seperately


```{r}

#Alpha diversity analyses

#make subsets of each host taxa for alpha diversity analyses
rubida <- clean_data %>% subset_samples(Host_Taxa == "Trubida")
protracta <- clean_data %>% subset_samples(Host_Taxa == "Tprotracta")
gerstaeckeri <- clean_data %>%  subset_samples(Host_Taxa == "Tgerstaeckeri")
lecticularia <- clean_data %>% subset_samples(Host_Taxa == "Tlecticularia")
sanguisuga <- clean_data %>% subset_samples(Host_Taxa == "Tsanguisuga")


### Alpha diversity analysis for ontogeny in each host taxa


# alpha diversity analysis of host taxa: rubida 
Figure1B <-plot_anova_diversity(rubida, method = c("richness", "shannon"), 
                          grouping_column = "Instar", pValueCutoff = 0.05)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/alphadiversity_analyses/Figure1B.pdf",width=8)#change the path for your computer
print(Figure1B)
dev.off()


# alpha diversity analysis of host taxa: gerstaeckeri 
Supplementing_Figure_1B_A <- plot_anova_diversity(gerstaeckeri, method = c("richness", "shannon"), 
                           grouping_column = "Instar", pValueCutoff = 0.05)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/alphadiversity_analyses/Supplementing_Figure_1B_A.pdf",width=8)#change the path for your computer
print(Supplementing_Figure_1B_A)
dev.off()


# alpha diversity analysis of host taxa: protracta 
Supplementing_Figure_1B_B <- plot_anova_diversity(protracta, method = c("richness", "shannon"), 
                           grouping_column = "Instar", pValueCutoff = 0.05)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/alphadiversity_analyses/Supplementing_Figure_1B_B.pdf",width=8)#change the path for your computer
print(Supplementing_Figure_1B_B)
dev.off()

# alpha diversity analysis of host taxa: sanguisuga 
Supplementing_Figure_1B_C <- plot_anova_diversity(sanguisuga, method = c("richness", "shannon"),
                           grouping_column = "Instar", pValueCutoff = 0.1)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/alphadiversity_analyses/Supplementing_Figure_1B_C.pdf",width=8)#change the path for your computer
print(Supplementing_Figure_1B_C)
dev.off()

# alpha diversity analysis of host taxa: lecticularia
Supplementing_Figure_1B_D <- plot_anova_diversity(lecticularia, method = c("richness", "shannon"),
                           grouping_column = "Instar", pValueCutoff = 0.05)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/alphadiversity_analyses/Supplementing_Figure_1B_D.pdf",width=8)#change the path for your computer
print(Supplementing_Figure_1B_D)
dev.off()


```

#Ordination analyses 


```{r}

# make subsets for ordination analyses
rubida <- clean_data %>% subset_samples(Host_Taxa == "Trubida")
chaparral <- clean_data %>% subset_samples(Locality == "Chaparral")
tucson <- clean_data %>% subset_samples(Locality == "UADS" | Locality == "LCNCA")
young <- clean_data %>% subset_samples(Instar == "L1"|Instar == "L2"|Instar == "L3")
Instar_range <- clean_data %>% subset_samples(Instar_range == "L1_3"|Instar_range == "L4_6")
rubida_UADSnest_young <- clean_data %>% subset_samples(Host_Taxa == "Trubida" & House == "nest" & Instar_range == "L1_3" & Locality == "UADS" & Nest != "nest6")

# NMDS on rubida ontogeny
rubida_nmds <- ordinate(
  physeq = rubida, 
  method = "NMDS", 
  distance = "bray"
)
## Stress = 0.15
Figure1C<-plot_ordination(
  physeq = rubida,
  ordination = rubida_nmds,
  color = "Instar",
  shape = "Instar",
  title = "NMDS of Rubida ontogeny") + 
  scale_color_viridis(option="plasma", discrete = TRUE, begin = 0.2, end = 0.9, direction = -1) +
  theme(panel.grid.major = element_line(size = 0.05, linetype = 'solid', colour = "white"),
        panel.grid.minor = element_line(size = 0.05, linetype = 'solid', colour = "white"),
        plot.background=element_rect(fill = "grey90"),
        panel.background = element_rect(fill = 'black'),
        axis.line = element_line(colour = "white"),) +
  geom_point(alpha = 1, size = 4) +
  stat_ellipse(geom='polygon', aes(colour=Instar, fill=Instar), alpha = 0.1)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/ordination_analyses/Figure1C.pdf",width=8)#change the path for your computer
print(Figure1C)
dev.off()

## PERMANOVA ON ONTOGENY
rubida_bray <- phyloseq::distance(rubida, method = "bray")
rubida_df <- data.frame(sample_data(rubida))
adonis(rubida_bray ~ Instar, data = rubida_df, permutations = 999, strata = rubida_df$Locality)
## Beta dispersion
beta1 <- betadisper(rubida_bray, rubida_df$Instar, type = "median", bias.adjust = TRUE)
permutest(beta1, pairwise = TRUE, permutations = 999, model = "direct")



##NMDS on young instar species-specific differences
young_nmds <- ordinate(
  physeq = young, 
  method = "NMDS", 
  distance = "bray"
)
### stress = ~0.2
Figure3<-plot_ordination(
  physeq = young,
  ordination = young_nmds,
  color = "Host_Taxa",
  shape = "Host_Taxa",
  title = "Young instars") + 
  scale_color_viridis(option = "plasma", discrete = TRUE, begin = 0.2, end = 0.9)+
  theme(panel.grid.major = element_line(size = 0.02, linetype = 'solid', colour = "black"),
        panel.grid.minor = element_line(size = 0.02, linetype = 'solid', colour = "black"),
        plot.background=element_rect(fill = "white"),
        panel.background = element_rect(fill = 'white'),
        axis.line = element_line(colour = "black"),) +
  geom_point(alpha = 1, size = 4)+
  stat_ellipse(geom='polygon', aes(colour=Host_Taxa, fill=Host_Taxa), alpha = 0.1, level = 0.95)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/ordination_analyses/Figure3.pdf",width=8)#change the path for your computer
print(Figure3)
dev.off()

## PERMANOVA on young instars
young_bray <- phyloseq::distance(young, method = "bray")
young_df <- data.frame(sample_data(young))
adonis(young_bray ~ Host_Taxa, data = young_df) 
## Beta dispersion
beta4 <- betadisper(young_bray, young_df$Host_Taxa)
permutest(beta4, pairwise = TRUE)



#NMDS on multi host taxa in same nest from Chaparral, TX
chap_nmds <- ordinate(
  physeq = chaparral, 
  method = "NMDS", 
  distance = "bray"
)
## 0.09 stress
Figure4<-plot_ordination(
  physeq = chaparral,
  ordination = chap_nmds,
  color = "Host_Taxa",
  shape = "Host_Taxa",
  title = "NMDS of Chaparral Multi-Species Nest") + 
  scale_color_viridis(option="plasma", discrete = TRUE, begin = 0.5, end = 0.8, direction = 1) +
  theme(panel.grid.major = element_line(size = 0.02, linetype = 'solid', colour = "black"),
        panel.grid.minor = element_line(size = 0.02, linetype = 'solid', colour = "black"),
        plot.background=element_rect(fill = "white"),
        panel.background = element_rect(fill = 'white'),
        axis.line = element_line(colour = "black"),) +
  geom_point(alpha = 1, size = 4) +
  geom_text(aes(label=Instar),hjust=1, vjust=0, size=3, colour = "black")+ 
  stat_ellipse(geom='polygon', aes(colour=Host_Taxa, fill=Host_Taxa), alpha = 0.1, level = 0.95)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/ordination_analyses/Figure4.pdf",width=8)#change the path for your computer
print(Figure4)
dev.off()

##PERMANOVA ON CHAPARRAL
chap_bray <- phyloseq::distance(chaparral, method = "bray")
chap_df <- data.frame(sample_data(chaparral))
adonis(chap_bray ~ Host_Taxa, data = chap_df, permutations = 999, strata = chap_df$Instar) #27% of the variation is species level
## Beta dispersion
beta2 <- betadisper(chap_bray, chap_df$Host_Taxa)
permutest(beta2, pairwise = TRUE)



## NMDS on rubida from two locations in Arizona
tuc_nmds <- ordinate(
  physeq = tucson, 
  method = "NMDS", 
  distance = "bray"
)
## 0.17 stress
Figure6<-plot_ordination(
  physeq = tucson,
  ordination = tuc_nmds,
  color = "Locality",
  shape = "Instar_range",
  title = "NMDS of Tucson rubida") + 
  scale_color_viridis(option = "plasma", discrete = TRUE, begin = 0.3, end = 0.8)+
  theme(panel.grid.major = element_line(size = 0.02, linetype = 'solid', colour = "black"),
        panel.grid.minor = element_line(size = 0.02, linetype = 'solid', colour = "black"),
        plot.background=element_rect(fill = "gray90"),
        panel.background = element_rect(fill = 'white'),
        axis.line = element_line(colour = "black"),) +
  geom_point(alpha = 1, size = 4) +
  #geom_text(aes(label=Instar),hjust=1, vjust=0, size=3, colour = "black")+ 
  stat_ellipse(geom='polygon', aes(colour=Locality, fill=Locality), alpha = 0.1, level = 0.95)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/ordination_analyses/Figure6.pdf",width=8)#change the path for your computer
print(Figure6)
dev.off()


## PERMANOVA ON TUCSON NEST RUBIDA
tuc_bray <- phyloseq::distance(tucson, method = "bray")
tuc_df <- data.frame(sample_data(tucson))
adonis(tuc_bray ~ Locality*Instar, data = tuc_df)
## Beta dispersion
beta3 <- betadisper(tuc_bray, tuc_df$Locality)
permutest(beta3)


#ordination analyses using jaccard in whole ultra datset
Instar_range_jaccard <- distance(Instar_range, "jaccard")
Instar_range_df <- as(sample_data(Instar_range), "data.frame")
p2 <- plot_ordination(Instar_range, Instar_range_jaccard, color = "Instar_range")
p2 + theme_bw() + theme(text = element_text(size = 16)) + geom_point(size = 4) + stat_ellipse(aes(group =Instar_range))
p2


#Permanova for the instar range in whole ultra dataset
adonis_Instar_range <- adonis(Instar_range_jaccard ~ Instar_range, data = Instar_range_df)
adonis_Instar_range

#betadiseprsion for the instar range in whole dataset
groups <- Instar_range_df[["Instar_range"]]
mod <- betadisper(Instar_range_jaccard, groups)
anova(mod)

#the dispersion is different between groups, then examine
plot(mod)

pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/ordination_analyses/Additional_File_5.pdf",width=8)#change the path for your computer
print(Additional_File_5<-boxplot(mod))
dev.off()


#make a subset of young rubida from UADS nest samples



## NMDS on young rubida from UADS nest samples
rubida_UADSnest_young_nmds <- ordinate(
  physeq = rubida_UADSnest_young, 
  method = "NMDS", 
  distance = "bray"
)

#plotting
Additional_File_6<-plot_ordination(
  physeq = rubida_UADSnest_young,
  ordination = rubida_UADSnest_young_nmds,
  color = "Nest",
  shape = "Nest",
  title = "NMDS of rubida in UADS nest samples") + 
  scale_color_viridis(option = "plasma", discrete = TRUE, begin = 0.2, end = 0.9)+
  theme(panel.grid.major = element_line(size = 0.02, linetype = 'solid', colour = "black"),
        panel.grid.minor = element_line(size = 0.02, linetype = 'solid', colour = "black"),
        plot.background=element_rect(fill = "white"),
        panel.background = element_rect(fill = 'white'),
        axis.line = element_line(colour = "black"),) +
  geom_point(alpha = 1, size = 4)+
  stat_ellipse(geom='polygon', aes(colour=Nest, fill=observed), alpha = 0.5, level = 0.95)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultradata_analyses/ordination_analyses/Additional_File_6.pdf",width=8)#change the path for your computer
print(Additional_File_6)
dev.off()



```

#Taxonomy profile for each host taxa

```{r}

#visualization of taxonomy profile

#Choose level of taxa to better visualization 
clean_data_gen<-taxa_level(clean_data, "Genus")

#normalize the data
clean_data_barplotgen <- normalise_data(clean_data_gen, norm.method = "relative")

#make required subsets for taxonomy profiling
rubida_ontogeny <- clean_data_barplotgen %>% subset_samples(Host_Taxa == "Trubida")
gerst_ontogeny <-  clean_data_barplotgen %>% subset_samples(Host_Taxa == "Tgerstaeckeri")
protra_ontogeny <- clean_data_barplotgen %>% subset_samples(Host_Taxa == "Tprotracta")
sang <- clean_data_barplotgen %>% subset_samples(Host_Taxa == "Tsanguisuga")
lec <- clean_data_barplotgen %>% subset_samples(Host_Taxa == "Tlecticularia")
nest2 <- clean_data_barplotgen %>% subset_samples(Locality == "Chaparral")

# Rubida only - across instars - genus level
Figure1A <- plot_taxa(rubida_ontogeny, grouping_column = "Instar",
                        method = "hellinger", number.taxa = 20, filename = NULL)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/taxonomyprofile_analyses/Figure1A.pdf",width=8)#change the path for your computer
print(Figure1A)
dev.off()


# For chaparral nest 2 - species difference - genus level
Figure4 <- plot_taxa(nest2, grouping_column = "Host_Taxa",
                      method = "hellinger", number.taxa = 20, filename = NULL)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/taxonomyprofile_analyses/Figure4.pdf",width=8)#change the path for your computer
print(Figure4)
dev.off()


# Gerstaeckeri only - across instars - genus level
Supplementing_Figure_1B_A <- plot_taxa(gerst_ontogeny, grouping_column = "Instar",
                       method = "hellinger", number.taxa = 20, filename = NULL)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/taxonomyprofile_analyses/Supplementing_Figure_1B_A.pdf",width=8)#change the path for your computer
print(Supplementing_Figure_1B_A)
dev.off()



## Protracta ontogeny - genus level
Supplementing_Figure_1B_B <- plot_taxa(protra_ontogeny, grouping_column = "Instar",
                        method = "hellinger", number.taxa = 20, filename = NULL)

pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/taxonomyprofile_analyses/Supplementing_Figure_1B_B.pdf",width=8)#change the path for your computer
print(Supplementing_Figure_1B_B)
dev.off()


## Sanguisuga ontogeny -genus level
Supplementing_Figure_1B_C <- plot_taxa(sang, grouping_column = "Instar",
                      method = "hellinger", number.taxa = 20, filename = NULL)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/taxonomyprofile_analyses/Supplementing_Figure_1B_C.pdf",width=8)#change the path for your computer
print(Supplementing_Figure_1B_C)
dev.off()


#Leticularia ontogeny - genus level
Supplementing_Figure_1B_D <- plot_taxa(lec, grouping_column = "Instar",
                        method = "hellinger", number.taxa = 20, filename = NULL)
pdf("D:/Czech/triatomine_manuscript/MS-Triatominae/results/ultracleandata_analyses/taxonomyprofile_analyses/Supplementing_Figure_1B_D.pdf",width=8)#change the path for your computer
print(Supplementing_Figure_1B_D)
dev.off()


```


